# Generated by Django 6.1.1 on 2026-10-03 15:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0002_remove_equipment_equipment_daily_rate_gt_zero_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('INSPECTION', 'Inspection'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue'), ('EXPIRED', 'Expired')], default='PENDING', max_length=40)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_rentals', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rentals', to='locations.location')),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_rentals', to='locations.location')),
            ],
            options={
                'db_table': 'Rental',
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_days', models.PositiveIntegerField(default=1)),
                ('unit_daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('INSPECTION', 'Inspection'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue'), ('EXPIRED', 'Expired')], default='PENDING', max_length=40)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_rental_items', to='equipments.equipment')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='rentals.rental')),
            ],
            options={
                'db_table': 'Rental_Item',
            },
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='rental_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='rental_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('late_fee__gte', 0)), name='rental_late_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('damage_charge__gte', 0)), name='rental_damage_charge_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('security_deposit__gte', 0)), name='rental_security_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='rental_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='rental_item_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_daily_rate__gte', 0)), name='rental_item_daily_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('security_deposit__gte', 0)), name='rental_item_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('late_fee__gte', 0)), name='rental_item_late_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rentalitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='rental_item_line_total_nonnegative'),
        ),
    ]
