# Generated by Django 6.1.1 on 2026-09-27 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='start_at',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
