# Generated by Django 6.1.1 on 2026-09-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('unavailable', 'Unavailable')], default='active', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('replacement_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipments.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='locations.location')),
            ],
            options={
                'db_table': 'equipments',
                'constraints': [models.CheckConstraint(condition=models.Q(('daily_rate__gt', 0)), name='equipment_daily_rate_gt_zero'), models.CheckConstraint(condition=models.Q(('weekly_rate__gt', 0)), name='equipment_weekly_rate_gt_zero'), models.CheckConstraint(condition=models.Q(('security_deposit__gt', 0)), name='equipment_security_deposit_gt_zero'), models.CheckConstraint(condition=models.Q(('replacement_value__gt', 0)), name='equipment_replacement_value_gt_zero')],
            },
        ),
    ]
