# Generated by Django 6.1.1 on 2026-09-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='equipment_daily_rate_gt_zero',
        ),
        migrations.RemoveConstraint(
            model_name='equipment',
            name='equipment_weekly_rate_gt_zero',
        ),
        migrations.RemoveConstraint(
            model_name='equipment',
            name='equipment_security_deposit_gt_zero',
        ),
        migrations.RemoveConstraint(
            model_name='equipment',
            name='equipment_replacement_value_gt_zero',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_equipment', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
